package com.pastryshop.pastry_backend.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.Field;

@Document(collection = "products")
public class Product {

    @Id
    private String id;

    private String name;

    private String imageUrl;

    // Price without benefit (cost price)
    private double purchasePrice;

    // Price for selling
    private double sellingPrice;

    // Stock quantity
    private int quantity;

    // Number of times sold
    private int numberOfSales;

    // Total benefit generated by this product
    private double totalBenefit;

    /* ===================== */
    /* GETTERS & SETTERS     */
    /* ===================== */

    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getImageUrl() { return imageUrl; }
    public void setImageUrl(String imageUrl) { this.imageUrl = imageUrl; }

    public double getPurchasePrice() { return purchasePrice; }
    public void setPurchasePrice(double purchasePrice) {
        this.purchasePrice = purchasePrice;
    }

    public double getSellingPrice() { return sellingPrice; }
    public void setSellingPrice(double sellingPrice) {
        this.sellingPrice = sellingPrice;
    }

    public int getQuantity() { return quantity; }
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public int getNumberOfSales() { return numberOfSales; }
    public void setNumberOfSales(int numberOfSales) {
        this.numberOfSales = numberOfSales;
    }

    public double getTotalBenefit() { return totalBenefit; }

    /* ===================== */
    /* BUSINESS METHODS      */
    /* ===================== */

    public void updateTotalBenefit(int soldQuantity) {
        double benefitPerUnit = sellingPrice - purchasePrice;
        this.totalBenefit += benefitPerUnit * soldQuantity;
    }
}
